### PR TITLE
Create a distance matrix between query sequences and reference sequences

### PR DESCRIPTION
**Pull request by GopiGugan**
* #88

### CODE REVIEW

**Comment by GopiGugan** [comment]
Unable to test on RDP5. Program crashed after loading sequences. 

Merging into `dev`

**Comment by darrenpmartin** [comment]
Hi Gopi - could you send me the alignment that crashed in RDP5. I'll try
figure out what went wrong

**Comment by GopiGugan** [comment]
Hi @darrenpmartin - I just tried on RDP v5.57 and got the following error when doing the "full query vs reference recombination scan": 

image


I've attached the alignment. Thanks!

[test.fasta.zip](https://github.com/user-attachments/files/15987934/test.fasta.zip)

**Comment by darrenpmartin** [comment]
THanks for this.

**Comment by darrenpmartin** [comment]
Hi Gopi - did you get the error during the scan or when you started
clicking on events in the table on the top right panel?  I fixed a bug that
caused a crash when you click on event 2 in the table but not sure if thats
the one you encountered.

**Comment by GopiGugan** [comment]
> Hi Gopi - did you get the error during the scan or when you started clicking on events in the table on the top right panel? I fixed a bug that caused a crash when you click on event 2 in the table but not sure if thats the one you encountered.

Hi @darrenpmartin, I got the error during the scan

**Comment by darrenpmartin** [comment]
OK then I assume you must be using different program settings t me - could
you send the file rdp.ini to me (it is in the directory where you have rdp5
installed)

Darren

**Comment by darrenpmartin** [comment]
OK no worries found the problem (tt was related to the progress bar during
the bootscan part of the analysis).
if you'd like you can download a fixed version of the RDP5.exe here:
https://web.cbio.uct.ac.za/~darren/rdp5.exe

Use it to the replace the one that you currently have installed (likely in
the c:/program files x86/rdp5 directory)

Darren

**Pull request merged**
