### PR TITLE
Be careful about importing mpi4py and give the user a way to not use MPI

### PR DESCRIPTION
**Pull request by terrycojones**

### CODE REVIEW

**Comment by terrycojones** [comment]
Don't merge this one yet - I'll also skip the `tests/test_mpi.py` if `mpi4py` is not installed.

**Comment by terrycojones** [comment]
OK, this should be better.

**Comment by ArtPoon** [comment]
Thanks @terrycojones.  Usually we do PRs to the `dev` branch but this looks like it should be ok for a hot fix.  I am out of town at a conference right now but I'll do some testing when I get back, or I'll ask @WilliamZekaiWang or @GopiGugan.

**Comment by WilliamZekaiWang** [comment]
Thank you for all the help, but I think it's a bit harder for users if we add a specific argument to the init use `mpi` rather than the auto detection. In terms of the unittest changes, I think it's a good addition so that they won't fail with it not installed. Will be adding in next set of changes

**Pull request closed without merging**
