### PR TITLE
Iss64

### PR DESCRIPTION
**Pull request by SandeepThokala**

### CODE REVIEW

**Comment by ArtPoon** [comment]
Waiting on expanding unit test coverage, see #67

**Review by pmagbor — COMMENTED** [review]
Overall, I didn't identify any issues with the modifications made to the code. Most of the unit tests passed for me locally except `test_three_seq.py` and `test_geneconv.py`.  @SandeepThokala confirmed that the 3seq test fails on Windows because a binary is used (noted in the readme). However, geneconv failed for `test_parse_results` due to problems generating `long.frags` but it seems to be working for @SandeepThokala locally and on Jesry so it may be a problem with my machine.

**Comment by pmagbor** [comment]
Just a few errors I found when attempting to run it as a user:

**Comment by SandeepThokala** [comment]
* Fixed `OpenRDP as a Python module option with scanner requires ref_seq as an argument rather than it being optional as described in the README` in the recent commit
* Fluctuations in the output is caused by this multiprocessing block
https://github.com/PoonLab/OpenRDP/blob/838eef2f0ef1699194c670f3f6f9e1ae3e2a64e2/openrdp/bootscan.py#L294-L297

**Pull request merged**
